version: "3.9"
services:
  clothing-model:
    image: zoomcamp-model:xception-v4-001
  gateway:
    image: zoomcamp-gateway:002
    environment:
      - TF_SERVING_HOST=clothing-model:8500
    ports:
      - "9696:9696"